package life.yl.community.mapper;

import life.yl.community.model.Question;
import life.yl.community.model.QuestionExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface QuestionExtMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Fri Dec 06 18:01:47 CST 2019
     */
    int incView(Question record);

    int incCommentCount(Question record);
}